[programs.localnet]
hello_anchor_message = "4Avv9uQe4j3KxoMaHzCHEhiNnyaio56AkAcucCDN5d3G"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/bmstar/.config/solana/id.json"

# [provider]
# cluster = "devnet"
# wallet = "/home/bmstar/work/keys/my-keypair.json"


[scripts]
test = "mocha -t 1000000 tests/"
